# Osceola County-specific configuration
CONFIG = {
    'county_code': 'OSCEOLA',
    'column_mapping': {
        'parcel_strap': 'Parcel/Strap',
        'property_address': 'Property Address',
        'date_sold': 'Date Sold',
        'price': 'Price',
        'book_pg': 'Book-Pg',
        'bed': 'Bed',
        'bath': 'Bath',
        'pool': 'Pool',
        'sqft': 'SqFt',
        'yos': 'YOS',
        'sellers': 'Seller(s)',
        'buyers': 'Buyer(s)',
        'deed_code': 'Deed Code',
        'mailing_address_1': 'Mailing Address 1',
        'mailing_address_2': 'Mailing Address 2',
        'mailing_address_3': 'Mailing Address 3',
        'mailing_city': 'Mailing City',
        'mailing_state': 'Mailing State',
        'mailing_zip_code': 'Mailing Zip Code',
        'mailing_country': 'Mailing Country',
        'site_city': 'Site City',
        'site_zip': 'Site Zip',
        'adj_price': 'Adj Price',
        'dos': 'DOS',
        'price_per_sqft': 'Price Per Sqft',
        'nh_cd': 'Nh Cd',
        'neighborhood': 'Neighborhood',
        'sub': 'Sub',
        'sub_division': 'Sub Division',
        'gross_ar': 'Gross Ar',
        'acreage': 'Acreage',
        'yr_roll': 'Yr Roll',
        'dor_cd': 'DOR Cd',
        'dor_description': 'DOR Description',
        'trns_cd': 'Trns Cd',
        'qu_flg': 'Qu flg',
        'vi': 'Vi',
        'grantors': 'Grantors',
        'all_grantees': 'All Grantees',
        'or_book': 'OR Book',
        'or_page': 'OR Page',
        'high_school_id': 'High School Id',
        'high_school': 'High School',
        'middle_school_id': 'Middle School Id',
        'middle_school': 'Middle School',
        'elementary_school_id': 'Elementary School Id',
        'elementary_school': 'Elementary School',
        'street': 'Street',
        'sales_analysis_id': 'Sales Analysis Id',
        'sales_ratio': 'Sales Ratio',
        'rea_cd': 'Rea Cd',
        'rea_description': 'Rea Description',
        'jst_val': 'Jst Val',
        'ayb': 'AYB',
        'multi_parcel': 'Multi Parcel',
        'book_page': 'Book Page',
        'is_primary': 'Is Primary',
        'is_secondary': 'Is Secondary',
        'market_area1': 'Market Area1',
        'market_area1_description': 'Market Area1 Description',
        'market_area2': 'Market Area2',
        'hotel_units': 'Hotel Units',
        'apt_units': 'Apt Units'
    },
    'schema_name': 'public',
    'table_name': 'property_sales',
    'table_columns': [
        'county_code', 'parcel_strap', 'property_address', 'date_sold', 'price', 'book_pg', 'bed', 'bath',
        'pool', 'sqft', 'yos', 'sellers', 'buyers', 'deed_code', 'mailing_address_1',
        'mailing_address_2', 'mailing_address_3', 'mailing_city', 'mailing_state',
        'mailing_zip_code', 'mailing_country', 'site_city', 'site_zip', 'adj_price',
        'dos', 'price_per_sqft', 'nh_cd', 'neighborhood', 'sub', 'sub_division',
        'gross_ar', 'acreage', 'yr_roll', 'dor_cd', 'dor_description', 'trns_cd',
        'qu_flg', 'vi', 'grantors', 'all_grantees', 'or_book', 'or_page',
        'high_school_id', 'high_school', 'middle_school_id', 'middle_school',
        'elementary_school_id', 'elementary_school', 'street', 'sales_analysis_id',
        'sales_ratio', 'rea_cd', 'rea_description', 'jst_val', 'ayb', 'multi_parcel',
        'book_page', 'is_primary', 'is_secondary', 'market_area1',
        'market_area1_description', 'market_area2', 'hotel_units', 'apt_units'
    ]
}